version: '3.8'
services:  
  mysql:
    container_name: mysql-wanted-dev
    platform: linux/x86_64
    image: mysql:8.0.25
    restart: always
    ports:
      - 3310:3306
    volumes:
      - './dev-db-data:/var/lib/mysql'
      - ./db/config/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_DATABASE=wanted-board
      - MYSQL_ROOT_PASSWORD=password